Server:
  Port: 8085
  BindIp: "localhost"

Observability:
  Port: 9090
  BindIp: "localhost"

DataDir: "/usr/share/etna-finance/data"

Auth:
  # Hash key and Block key MUST be updated in production and kept secret
  HashKey:      "He4wazahwo6oer0iuNg6chah1Phoh4Eimo7ku0boom8ia8joichieVei8aeNga2o"
  BlockKey:     "ma6eiTeChie6moh3mei5nohth2uqu7ah"
  UserStore:
    Type: static
    Users:
      - Name: "demo"
        Pw: "demo"
        Enabled: true

Env:
  Loglevel: "info"
  Production: false