name: GO
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v4
      ## Setup GO
      - name: Setup Go 1.24.2
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      # Install go-licence-detector
      - name: Install go-licence-detector
        run: |
          go install github.com/elastic/go-licence-detector@latest

      - name: verify code
        run: make verify

